name: Emit event on push
on: push

jobs:
  build:
    name: External workflow dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@fix-json-error
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repo: "@"
          event_type: sample_push
          debug: 1
          message: |
            {
              "foo": "bar",
              "multiline": "
                Testing a multiline JSON string
              ",
              "baz": 1234
            }
